[package]
authors = ["Yohai Berreby (yberreby) <yohaiberreby@gmail.com>"]
description = "A lexer for the Go programming language"
license = "MIT/Apache-2.0"
name = "rgo-lexer"
repository = "https://github.com/yberreby/rgo"
version = "0.1.0"

[dependencies.rgo-token]
path = "../token"
